# Generated by Django 4.2.6 on 2023-11-28 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AplikasiLayananUMKM', '0002_menu_gambar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='gambar',
            field=models.ImageField(null=True, upload_to='img/'),
        ),
    ]
