# Generated by Django 4.2.6 on 2023-11-30 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AplikasiLayananUMKM', '0003_alter_menu_gambar'),
    ]

    operations = [
        migrations.CreateModel(
            name='AishTea',
            fields=[
                ('menu_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='AplikasiLayananUMKM.menu')),
            ],
            bases=('AplikasiLayananUMKM.menu',),
        ),
        migrations.CreateModel(
            name='Saguku',
            fields=[
                ('menu_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='AplikasiLayananUMKM.menu')),
            ],
            bases=('AplikasiLayananUMKM.menu',),
        ),
        migrations.CreateModel(
            name='Wang',
            fields=[
                ('menu_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='AplikasiLayananUMKM.menu')),
            ],
            bases=('AplikasiLayananUMKM.menu',),
        ),
    ]
